
name: CARS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install --upgrade cython numpy
        pip install --upgrade numba
        pip install .[dev,docs,notebook,pandora_mccnn]
        pip list
    - name: Unit Tests
      run: |
        pytest -m "unit_tests" -o log_cli=true -o log_cli_level=INFO
    - name: Lint Tests
      run: |
        echo "Lint test"
        isort --check cars tests
        black --check cars tests
        flake8 cars tests
        pylint cars tests --rcfile=.pylintrc --output-format=parseable | tee pylint-report.txt # pipefail to propagate pylint exit code in bash
